# WARNING!!!: DO NOT EDIT THIS FILE TO AVOID GIT CONFLICT, REACH OUT TO YOUR TEAM LEAD FOR UPDATE

from sqlmodel import create_engine
from sqlmodel import Session
import os

# database connection takes in db url, defining the db using sql lite
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./e_library.db")

# SQLModel engine
engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False}
    if DATABASE_URL.startswith("sqlite")
    else {},
)


def get_db():
    with Session(engine) as session:
        yield session
