name: Backend CI Pipeline

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: echo "Placeholder for backend setup (Node.js/Express, etc.)"

      - name: Install Dependencies
        run: echo "Placeholder for installing backend dependencies"

      - name: Run Tests
        run: echo "Placeholder for running backend tests"

      - name: Build Docker Image
        run: echo "Placeholder for backend Docker build & push"